### Acceso a elementos de un array

In [4]:
import numpy as np

mi_array = np.arange(100).reshape(10,10)

print(mi_array)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [10]:
mi_array[0,2] # Filas, columnas

np.int64(2)

In [8]:
mi_array[1:4] # Filas desde la 1 hasta la 4

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [7]:
mi_array[1:4, 0:2] # Filas desde la 1 hasta la 4 y columnas desde la 0 hasta la 2

array([[10, 11],
       [20, 21],
       [30, 31]])

In [11]:
mi_array[0:6:2] # Filas desde la 0 hasta la 6 de 2 en 2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [12]:
mi_array[::-1] # Invertir el array

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [13]:
mi_array[:,::-1] # Invertir las columnas

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1,  0],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10],
       [29, 28, 27, 26, 25, 24, 23, 22, 21, 20],
       [39, 38, 37, 36, 35, 34, 33, 32, 31, 30],
       [49, 48, 47, 46, 45, 44, 43, 42, 41, 40],
       [59, 58, 57, 56, 55, 54, 53, 52, 51, 50],
       [69, 68, 67, 66, 65, 64, 63, 62, 61, 60],
       [79, 78, 77, 76, 75, 74, 73, 72, 71, 70],
       [89, 88, 87, 86, 85, 84, 83, 82, 81, 80],
       [99, 98, 97, 96, 95, 94, 93, 92, 91, 90]])

In [14]:
mi_array[:, [0,2,9]] # Seleccionar todas las columnas de las filas de la lista determinada

array([[ 0,  2,  9],
       [10, 12, 19],
       [20, 22, 29],
       [30, 32, 39],
       [40, 42, 49],
       [50, 52, 59],
       [60, 62, 69],
       [70, 72, 79],
       [80, 82, 89],
       [90, 92, 99]])

In [ ]:
print(mi_array[-1]) # Seleccionar la última fila
print(mi_array[-2]) # Seleccionar la penúltima fila
print(mi_array[:,-1]) # Seleccionar la última columna
print(mi_array[:,-2]) # Seleccionar la penúltima columna

### Máscaras Booleanas