1. Crea un array con 15 números enteros aleatorios entre 1 y 100

In [2]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Para crear un array de numeros random enteros se utiliza la propiedad random y para que sea entero randint --- 
# --- np.random.randint(inicio, final, tamaño, tipo) ---

array_enteros = np.random.randint(1, 101, size=15)

# --- Imprimimos el resultado del array construido ---
print(array_enteros)

[75 36 51 85 84 24 17  5 96 34 94 10 26 27  5]



2. Multiplica todos los elementos del array usando un bucle y después usando un método de numpy.  
Compara los resultados

In [3]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Inicializamos la variable en 1 debido a que si lo inicializamos en 0 el valor resultante de aplicar la multiplicacion al recorrer el array es 0. ---
multi_array = 1
for numero in array_enteros:
    multi_array = multi_array * numero

print(f"La multiplicación resultante del array es: {multi_array}")

La multiplicación resultante del array es: -777715712


C:\Users\M7600\AppData\Local\Temp\ipykernel_8328\869333652.py:7: RuntimeWarning: overflow encountered in scalar multiply
  multi_array = multi_array * numero


3. Crea otro array con 15 números decimales aleatorios entre 0 y 1

In [4]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Para crear un array de numeros random decimales entre 0 y 1 se utiliza la propiedad random y para que sea entero rand --- 
# --- np.random.rand(tamaño) ---
array_decimales = np.random.rand(15)

print(array_decimales)

[0.28853576 0.28235187 0.52403561 0.47118341 0.4507675  0.5596062
 0.26395005 0.35035843 0.68296189 0.67343812 0.37772224 0.37199706
 0.9312736  0.51227138 0.42570549]


4. Suma los elementos de ambos arrays elementos por elemento.  
Resuélvelo usando un operador y después con una función de numpy.  
(Pista: busca en google que función de numpy hace esto)

In [5]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Suma utilizando operador + ---
suma_array = array_enteros + array_decimales

print(suma_array)

# --- Suma usando función del módulo de Numpy ---
suma_array_2 = np.add(array_enteros, array_decimales)

print(suma_array_2)

[75.28853576 36.28235187 51.52403561 85.47118341 84.4507675  24.5596062
 17.26395005  5.35035843 96.68296189 34.67343812 94.37772224 10.37199706
 26.9312736  27.51227138  5.42570549]
[75.28853576 36.28235187 51.52403561 85.47118341 84.4507675  24.5596062
 17.26395005  5.35035843 96.68296189 34.67343812 94.37772224 10.37199706
 26.9312736  27.51227138  5.42570549]


5. Ahora réstalos. Resuélvelo usando un operador y después con una función de numpy
(Pista: busca en google que función de numpy hace esto)

In [7]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Resta utilizando operador + ---
resta_array = array_enteros - array_decimales

print(resta_array)

# --- Resta usando función del módulo de Numpy ---
resta_array_2 = np.subtract(array_enteros, array_decimales)

print(resta_array_2)



[74.71146424 35.71764813 50.47596439 84.52881659 83.5492325  23.4403938
 16.73604995  4.64964157 95.31703811 33.32656188 93.62227776  9.62800294
 25.0687264  26.48772862  4.57429451]
[74.71146424 35.71764813 50.47596439 84.52881659 83.5492325  23.4403938
 16.73604995  4.64964157 95.31703811 33.32656188 93.62227776  9.62800294
 25.0687264  26.48772862  4.57429451]


6. Haz lo mismo con la multiplicación elemento por elemento. Usa un operador y después con una función de numpy.  
(Pista: busca en google que función de numpy hace esto)

In [9]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

multi_array = array_enteros * array_decimales

print(multi_array)

multi_array_2 = np.multiply(array_enteros, array_decimales)

print(multi_array_2)

[21.64018203 10.16466736 26.72581608 40.05058998 37.86447001 13.4305488
  4.48715082  1.75179217 65.56434191 22.89689604 35.50589092  3.71997062
 24.21311369 13.83132734  2.12852744]
[21.64018203 10.16466736 26.72581608 40.05058998 37.86447001 13.4305488
  4.48715082  1.75179217 65.56434191 22.89689604 35.50589092  3.71997062
 24.21311369 13.83132734  2.12852744]


7. Encuentra el valor más alto del primer array que has creado.


In [10]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

min_array = np.min(array_enteros)

print(min_array)

max_array = np.max(array_enteros)

print(max_array)

5
96


8. Calcula la media (mean), la mediana (median) y al deviación estandar (standard deviation) de los arrays  
(Nota: No nos importa el significado matemático de estos valores, lo importante es que encuentres que función de numpy necesitas.  
 Puedes hacer la búsqueda en castellano o en inglés, aunque en inglés muchas veces suele haber más resultados).

In [11]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- MEDIA ---
media_array = np.mean(array_enteros)

print(media_array)

media_array_2 = np.mean(array_decimales)

# --- MEDIANA ---
mediana_array = np.median(array_enteros)

print(mediana_array)

mediana_array_2 = np.median(array_decimales)

# --- DESVIACION ESTANDAR ---
desviacion_array = np.std(array_enteros)
print(desviacion_array)

desviacion_array_2 = np.std(array_decimales)
print(desviacion_array_2)

44.6
34.0
32.24241512872963
0.17449249678063714


9.  Crea un arrays lleno de 1s con una longitud dada por el usuario

In [12]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Pedimos al usuario que introduzca la longitud del array ---
longitud = int(input("Por favor introduce la longitud del array que desea obtener: "))

# --- Creamos el array de valores 1 segun la longitud expuesta o porporcionada por el usuario ---
array_ones = np.ones(longitud)

# --- Imprimimos por pantalla el array con la longitud dada por el usuario ---
print(array_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


10. Cambia la forma del array para que tenga una estructura de tipo (filas, columnas)

In [18]:
import numpy as np

longitud = int(input("Por favor introduce la longitud del array que desea obtener: "))
array_ones = np.ones(longitud)
print(array_ones)

filas = int(input("Por favor, ingrese el número de filas que desea que tenga el array: "))
columnas = int(input("Por favor, ingrese el número de columnas que desea que tenga el array: "))

# --- Módulo de Numpy --> reshape() ---
if (filas * columnas) == longitud:
    array_nuevo = np.reshape(array_ones, (filas, columnas))
    print("El array conformado es: \n", array_nuevo)
else:
    print("La cantidad de filas y columnas no es compatible con la longitud del array")

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
La cantidad de filas y columnas no es compatible con la longitud del array


11. Crea una “matriz identidad” con la misma forma que el array anterior (filas, columnas)

In [ ]:
import numpy as np

longitud = int(input("Por favor introduce la longitud del array que desea obtener: "))
array_ones = np.ones(longitud)
print(array_ones)

filas = int(input("Por favor, ingrese el número de filas que desea que tenga el array: "))
columnas = int(input("Por favor, ingrese el número de columnas que desea que tenga el array: "))

if (filas * columnas) == longitud:
    array_nuevo = np.reshape(array_ones, (filas, columnas))
    print("El array conformado es: \n", array_nuevo)

    if filas == columnas:
        matriz_identidad = np.eye(filas)
        print("La matriz identidad es: ", matriz_identidad)
    else:
        print("No se puede crear una matriz identidad con diferente numero de filas que de columnas")
    
else:
    print("La cantidad de filas y columnas no es compatible con la longitud del array")

12. Concatena ambas estructuras horizontalmente y verticalmente  
(Pista: Investiga el funcionamiento de concatenate() y de vstack() y hstack() de numpy)


In [ ]:
import numpy as np

longitud = int(input("Por favor introduce la longitud del array que desea obtener: "))
array_ones = np.ones(longitud)
print(array_ones)

filas = int(input("Por favor, ingrese el número de filas que desea que tenga el array: "))
columnas = int(input("Por favor, ingrese el número de columnas que desea que tenga el array: "))

if (filas * columnas) == longitud:
    array_nuevo = np.reshape(array_ones, (filas, columnas))
    print("El array conformado es: \n", array_nuevo)

    if filas == columnas:
        matriz_identidad = np.eye(filas)
        print("La matriz identidad es: ", matriz_identidad)

        # concatenar horizontalmente\n",
        concat_horizontal = np.hstack((nuevo_array, matriz_identidad))
        print("Concatenacion horizontal: ", concat_horizontal)
        
        # --- Concatenar vertical ---
        concat_vertical = np.vstack((nuevo_array, matriz_identidad))
        print("Concatenacion vertical: ", concat_vertical)
    else:
        print("No se puede crear una matriz identidad con diferente numero de filas que de columnas")
    
else:
    print("La cantidad de filas y columnas no es compatible con la longitud del array")