1. Crea un array_1 lleno ceros con una longitud de 8 elementos.

In [1]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Creamos un array_1 compuesto por un array de 8 posiciones inicializadas con valor 0 ---
array_1 = np.zeros(8)

# --- Imprimimos los valores asociados al array almacenado --- 
print(array_1)

[0. 0. 0. 0. 0. 0. 0. 0.]


2. Haz que todos los elementos de este array sean igual a 2

In [2]:
# --- Convertimos todos los valores del array almacenado en array_1 con valor 0 en valor 2 ---
array_1[:] = 2

print(array_1)

[2. 2. 2. 2. 2. 2. 2. 2.]


3. Crea un array_2 que contenga todos los números pares del 1 al 10.

In [8]:
array_2 = np.arange(2,11,2)

print(array_2)

[ 2  4  6  8 10]


4. Suma todos los elementos del array_2 usando un bucle y después usando un método de numpy. Compara los resultados

In [ ]:
# --- Inicializamos una variable con valor 0 para futura actualizacion en base a los valores que vamos a recorrer usando el bucle ---
suma_array = 0

for numero in array_2:
    suma_array = suma_array + numero

print(suma_array)

30
30


5. Revierte array_2 y guárdalo en una variable independiente.

In [15]:

array_independiente = array_2[::-1]

print(array_independiente)
print("----------------")
print(array_2)

array_2 == array_independiente


[10  8  6  4  2]
----------------
[ 2  4  6  8 10]


array([False, False,  True, False, False])

6. Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y array_2_revertido  
(Pista: Investiga el uso de intersect1d() de numpy)


In [ ]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Arrays almacenados ---
array_1 = np.zeros(8)
array_1[:] = 2
array_2 = np.arange(2,11,2)
array_independiente = array_2[::-1]

# --- Imprimimos por pantalla los arrays almacenados en la memoria ---
print(array_1)
print(array_2)
print(array_independiente)

# --- Obtención de los elementos comunes entre array_1 y array_2 --> funcion intersect1d() del modulo de numpy
interseccion_1 = np.intersect1d(array_1, array_2)
print(interseccion_1)


[2. 2. 2. 2. 2. 2. 2. 2.]
[ 2  4  6  8 10]
[10  8  6  4  2]
[2.]


7. Crea un arrays lleno de 1s con una longitud dada por el usuario

In [18]:
# --- Debemos importar el modulo de numpy que previamente hemos instalado en nuestro entorno de trabajo ---
import numpy as np

# --- Pedimos al usuario que introduzca la longitud del array ---
longitud = int(input("Por favor introduce la longitud del array que desea obtener: "))

# --- Creamos el array de valores 1 segun la longitud expuesta o porporcionada por el usuario ---
array_ones = np.ones(longitud)

# --- Imprimimos por pantalla el array con la longitud dada por el usuario ---
print(array_ones)

[1. 1. 1. 1. 1.]
